# NumPy
## Introduction
NumPy is a Python package for scientific computing that contains:
* multi-dimensional arrays and supporting functions
* basic linear algebra functions
* basic Fourier transforms

NumPy is intended to improve ease and efficiency of data handling and calculation.

## Instructions
Read through this Jupyter Notebook.  Execute the code cells to see the result.  Feel free to modify these cells, or add new cells, to experiment with the functionality.  

In the **Task** sections, add the necessary code to complete the task.

## Importing NumPy
NumPy is a package that must be installed in your virtual environment.  `numpy` is the package name for installation.  Once installed, it is imported into your Python code as follows:

In [1]:
import numpy as np

The `np` alias is frequently used as a short cut, so calls can be made such as `a = np.array([0, 1, 2, 3])`

## Creating NumPy Arrays
### `array()`
If you have an array like structure in Python, such as a list, it can be converted into a NumPy array as follows:

In [2]:
a = [0, 2, 10, -3, 2.5]  # A python list
print("a is variable type {}".format(type(a)))

b = np.array(a)
print("b is variable type {}".format(type(b)))

a is variable type <class 'list'>
b is variable type <class 'numpy.ndarray'>


Note that the type of variable contained in the array will depend on the data used to create the array.

In [3]:
c = np.array([0, 1, 2])
print("The 'c' numpy array is {}".format(c))
print("The type of variable in the 'c' array is {}".format(type(c[0])))

d = np.array([0, 1, 2.4])
print("The 'd' numpy array is {}".format(d))
print("The type of variable in the 'd' array is {}".format(type(d[0])))

d1 = np.array(["hello", "goodbye"])
print("The 'd1' numpy array is {}".format(d1))
print("The  type of variable in the 'd1' array is {}".format(type(d1[0])))

The 'c' numpy array is [0 1 2]
The type of variable in the 'c' array is <class 'numpy.int64'>
The 'd' numpy array is [0.  1.  2.4]
The type of variable in the 'd' array is <class 'numpy.float64'>
The 'd1' numpy array is ['hello' 'goodbye']
The  type of variable in the 'd1' array is <class 'numpy.str_'>


Note that integers are printed without a decimal point by NumPy.  Floats are printed with the decimal point.

Also, it is not common for strings to be used in NumPy arrays as the mathmatical functions in NumPy don't
provide much benefit for strings.  But, they can be used.

### `zeros()` and `ones()`
These two NumPy functions will create a new array filled with either zeros or ones of type `float`

In [4]:
e = np.zeros(5)
f = np.ones(8)
print(e)
print(f)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]


### `arange()`
The `arange()` function in NumPy will create an array with regularly incrementing values.  Examples:

In [5]:
g = np.arange(10)
print(g)

h = np.arange(2, 4, 0.2)
print(h)

[0 1 2 3 4 5 6 7 8 9]
[2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8]


### Task
In the cell below,

a. generate a NumPy array of the odd numbers from 3 to 13

b. generate a NumPy array counting down from 10 to 0

In [12]:
# Enter your code here

a = np.arange(3, 14, 2)
print(a)

b = np.arange(10, -1, -1)
print(b)


[ 3  5  7  9 11 13]
[10  9  8  7  6  5  4  3  2  1  0]


### `linspace()`
As its name implies, `linspace(a, b, c)` creates an array of linearly spaced values between two given values (`a` and `b`) and the number of elements in the array is specified by a third value (`c`).  Example:

In [13]:
i = np.linspace(1, 4, 6)
print(i)

[1.  1.6 2.2 2.8 3.4 4. ]


In the example above, an array of 6 members is generated with equally spaced values from 1 to 4.

### Task
In the cell below, generate a list of 15 numbers equally spaced from 10 to 20.

In [15]:
# Enter your code here
i = np.linspace(10, 20, 15)
print(i)

[10.         10.71428571 11.42857143 12.14285714 12.85714286 13.57142857
 14.28571429 15.         15.71428571 16.42857143 17.14285714 17.85714286
 18.57142857 19.28571429 20.        ]


## Multi-Dimensional Arrays
One of the improved functionality of NumPy arrays versus typical Python data structures is the ability to create multi-dimensional arrays.

In [16]:
one_d = np.zeros(10)
two_d = np.zeros((3, 5))  # Note that a tuple is required when more than 1 dimension is given

print("A one dimensional array:")
print(one_d)
print("A two dimensional array:")
print(two_d)

A one dimensional array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
A two dimensional array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Array Indexing
### 1-D arrays
Similar to lists in Python, the elements in a NumPy array are referenced using `[]` with the first element being 0.
Example:

In [17]:
j = np.array([2, 3, 4, 5, 6, 7, 8, 9])
print(j[0])
print(j[3])

2
5


You can also count backwards from the end of the array with the `-1` index being the last element of the array.

In [18]:
print(j[-1])
print(j[-3])

9
7


You can index sections of the array, such as `3:6`, that follows Python convention and returns the elements starting at 3 and ending with the element before 6.

In [19]:
print(j[3:6])

[5 6 7]


### Task
In the cell below, 
* generate a one-dimentional NumPy array with all the multiples of 5 from 5 to 95
* reference this array using an index to print out the value 35
* reference this array to print out the values from 50 to 65

In [26]:
# Enter your code here
a = np.arange(5, 96, 5)
print(a)

print(a[6])
print(a[9:13])

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
35
[50 55 60 65]


### 2-D arrays
See the various examples below for indexing two-dimensional arrays.

In [27]:
k0 = [0, 1, 2, 3]
k1 = [4, 5, 6, 7]
k2 = [8, 9, 10, 11]
k3 = [12, 13, 14, 15]
k = np.array([k0, k1, k2, k3])
print("k is:")
print(k)
print("")

print('k[1, 3] is {}'.format(k[1, 3]))
print('k[3, 1] is {}'.format(k[3, 1]))
print('k[2, -1] is {}'.format(k[2, -1]))
print('k[2, :] is {}'.format(k[2, :]))
print('k[:, 2] is {}'.format(k[:, 2]))

k is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

k[1, 3] is 7
k[3, 1] is 13
k[2, -1] is 11
k[2, :] is [ 8  9 10 11]
k[:, 2] is [ 2  6 10 14]


### Task
In the cell below:
* Generate and print a two-dimensional array that looks like this:
```
1 0 2
2 1 1
3 2 0
```
* Using an index to this array, print out the value `3`
* Using an index to this array, print out the row `2 1 1`
* Using an index to this array, print out the row
```
1
2
3
```
* If you want a challenge, write a loop to print out the diagonal `1 1 0`


In [33]:
# Enter your code here
k0 = [1, 0, 2]
k1 = [2, 1, 1]
k2 = [3, 2, 0]
k = np.array([k0, k1, k2])
print(k)

print(k[2,0])
print(k[1,:])
print(k[:,0])

for i in [0, 1, 2]:
    print(k[i, i])

[[1 0 2]
 [2 1 1]
 [3 2 0]]
3
[2 1 1]
[1 2 3]
1
1
0


## Math on Arrays
See some of the examples below for how math can be done on arrays.

In [34]:
x = np.arange(0, 5, 0.5)
print(x)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [35]:
y = x + 5
print(y)

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [36]:
y = x * 5
print(y)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [37]:
y = np.sin(x)
print(y)

[ 0.          0.47942554  0.84147098  0.99749499  0.90929743  0.59847214
  0.14112001 -0.35078323 -0.7568025  -0.97753012]


In [38]:
x1 = np.array([0, 1, 0, 0.5, 0, 1])
x2 = np.array([1, 2, 3, 4, 5, 6])
y = x1 * x2
print(y)


[0. 2. 0. 2. 0. 6.]


In [39]:
print(np.pi * x)
print(np.degrees(np.pi * x))
print(np.radians(180))

[ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061 14.13716694]
[  0.  90. 180. 270. 360. 450. 540. 630. 720. 810.]
3.141592653589793


### Task
In the cell below,
1. create and print an array with 10 elements that ranges from 0 to pi
2. create and print an array with the sine of the values from step 1
3. create and print an array with the cosine of the values from step 1
4. create and print an array with the tangent of the values from step 1
5. create and print an array where the step 2 array is divided by the step 3 array
6. create and print an array with the difference between the step 5 array and the step 4 array 

In [44]:
# Enter your code here
q1 = np.linspace(0, np.pi, 10)
print(q1)

q2 = np.sin(q1) 
print(q2)

q3 = np.cos(q1) 
print(q3)

q4 = np.tan(q1) 
print(q4)

q5 = q2/q3 
print(q5)

q6 = q5-q4
print(q6)

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]
[0.00000000e+00 3.42020143e-01 6.42787610e-01 8.66025404e-01
 9.84807753e-01 9.84807753e-01 8.66025404e-01 6.42787610e-01
 3.42020143e-01 1.22464680e-16]
[ 1.          0.93969262  0.76604444  0.5         0.17364818 -0.17364818
 -0.5        -0.76604444 -0.93969262 -1.        ]
[ 0.00000000e+00  3.63970234e-01  8.39099631e-01  1.73205081e+00
  5.67128182e+00 -5.67128182e+00 -1.73205081e+00 -8.39099631e-01
 -3.63970234e-01 -1.22464680e-16]
[ 0.00000000e+00  3.63970234e-01  8.39099631e-01  1.73205081e+00
  5.67128182e+00 -5.67128182e+00 -1.73205081e+00 -8.39099631e-01
 -3.63970234e-01 -1.22464680e-16]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
